window.HW_DATA.slides.push(...[
{"number":7,"module":"disparities","title":"What Regional Disparities Are","explanation":"Regional disparities are differences in quality of life, opportunity and access to resources between places. A region might be a country, a state, a city, a rural area or even a neighbourhood. When one place has better access to hospitals, schools, jobs, transport, clean water or safe housing than another, a disparity exists.

These differences can be caused by many factors. Economic conditions matter because wealthier regions often have more investment and employment. Infrastructure matters because roads, electricity, internet and public transport affect access to services. Education and healthcare can vary between regions. Environmental conditions such as drought, pollution, natural hazards and climate can also shape wellbeing.

Regional disparities are important because they create unequal life chances. A child’s opportunities may be influenced by where they are born or where their family can afford to live. Geographers study these patterns because wellbeing is not evenly distributed across space.

The key question is not only ‘Which place is better off?’ but also ‘Why are the differences there, who is affected, and what could reduce the gap?’","keyTerms":[{"term":"regional disparity","meaning":"a significant difference in wellbeing, opportunity or resources between places"},{"term":"infrastructure","meaning":"basic systems such as roads, electricity, water, internet and transport"},{"term":"spatial distribution","meaning":"the pattern of where something is located across space"}],"task":{"type":"compare","title":"Spot the disparity","prompt":"Compare an urban and a rural area. List three services that may differ and explain how one difference could affect wellbeing."}},
{"number":8,"module":"disparities","title":"Income and Employment Disparities","explanation":"Income and employment strongly influence economic wellbeing because they affect the resources people can access. Stable employment can provide money for food, housing, transport, healthcare, education and recreation. It can also provide routine, security, social contact and a sense of purpose.

When income is low or employment is insecure, people may have to make difficult choices between essential expenses. A family may delay medical treatment, move into cheaper housing or reduce spending on healthy food. Financial pressure can also affect mental health and family relationships.

However, average income must be interpreted carefully. A country can have a high average income while wealth is concentrated among a small group. A suburb can contain both high-income and low-income households. This means averages can hide inequality.

When comparing income between places, do not simply say that higher income means higher wellbeing. Explain the pathway: higher or more stable income can improve access to needs and opportunities, but wellbeing also depends on health, relationships, environment, culture and rights.","keyTerms":[{"term":"income disparity","meaning":"difference in income between people or places"},{"term":"financial security","meaning":"having enough reliable income to meet needs and manage expenses"},{"term":"average income","meaning":"the mean income across a population"},{"term":"inequality","meaning":"unequal distribution of resources or opportunities"}],"task":{"type":"data","title":"Income comparison","prompt":"Compare two countries or regions using income data. Explain two possible wellbeing effects and one limitation of using an average."}},
{"number":9,"module":"disparities","title":"Education Disparities","explanation":"Education disparities occur when people in different places have unequal access to schooling, different years of education or different quality of education. Education influences wellbeing because it develops literacy, knowledge and skills that can improve employment opportunities and income.

Education also supports decision-making. People who can access reliable information are often better able to understand healthcare advice, manage finances, participate in government and advocate for their rights. At a community level, education can support economic development and improve public awareness of health and environmental issues.

The number of years spent in school is one useful measure, but it does not tell us everything. Two countries may have similar average years of schooling but very different school quality, class sizes, teacher availability or access for girls, rural students or students with disability.

A good geographical explanation therefore connects education to opportunity while recognising that quantity and quality are not the same thing.","keyTerms":[{"term":"educational disparity","meaning":"unequal access to or outcomes from education"},{"term":"average years of schooling","meaning":"the average number of years of education completed by people"},{"term":"empowerment","meaning":"gaining knowledge or power to make choices and influence decisions"}],"task":{"type":"compare","title":"Schooling and opportunity","prompt":"Compare two countries using years of schooling. Explain how the difference could affect employment, health knowledge and political participation."}},
{"number":10,"module":"disparities","title":"Environmental and Pollution Disparities","explanation":"The environment can strongly influence wellbeing. Clean air, safe water, green space and protection from hazards can support physical and mental health. Pollution, unsafe water, extreme heat, flooding or bushfires can reduce quality of life and create long-term health and economic costs.

Air pollution is a useful example. Polluted air can contribute to breathing problems, heart disease and reduced ability to exercise outdoors. It can also increase healthcare costs and lead to missed work or school. Environmental damage can affect crops, forests and food production.

Environmental disparities occur because exposure is not equal. Some communities live closer to busy roads, industrial areas or polluted waterways. Others may have better access to parks, clean transport and environmental protections.

When we study an environmental disparity, we should look at both exposure and vulnerability. Two communities may experience the same hazard, but the one with weaker housing, healthcare or emergency services may suffer greater harm.","keyTerms":[{"term":"environmental disparity","meaning":"unequal environmental quality or hazard exposure between places"},{"term":"exposure","meaning":"the amount of contact a person or community has with a hazard"},{"term":"vulnerability","meaning":"how likely people are to be harmed by a hazard"},{"term":"AQI","meaning":"Air Quality Index, a measure used to describe air-pollution conditions"}],"task":{"type":"case","title":"Pollution pathway","prompt":"Build a chain: pollution source → exposure → health effect → economic or social effect."}},
{"number":11,"module":"disparities","title":"Happiness and Subjective Wellbeing","explanation":"Not every part of wellbeing can be measured with income, years of schooling or life expectancy. Happiness and life satisfaction are examples of subjective wellbeing because they are based on how people feel and evaluate their own lives.

Subjective wellbeing can be influenced by income and services, but also by relationships, trust, safety, freedom, culture, expectations and purpose. This explains why two people with similar material living conditions may report very different levels of happiness.

Countries with strong healthcare, education, social support and political stability often perform well in happiness measures, but this does not mean every person in those countries is happy. National averages can hide differences between groups.

The important lesson is that objective and subjective measures should be used together. Objective data tells us about living conditions. Subjective data tells us how people experience those conditions. Both are useful, but neither is complete on its own.","keyTerms":[{"term":"subjective wellbeing","meaning":"a person’s own evaluation of happiness and life satisfaction"},{"term":"objective indicator","meaning":"a measurable condition such as income, life expectancy or schooling"},{"term":"life satisfaction","meaning":"how positively a person evaluates their life overall"}],"task":{"type":"evaluate","title":"Can a rich country be unhappy?","prompt":"Give one reason wealth can support happiness and one reason a wealthy country could still contain low subjective wellbeing."}},
{"number":12,"module":"disparities","title":"Common Spatial Patterns of Disparity","explanation":"Regional disparities often follow recognisable spatial patterns. Urban and rural areas may differ because cities usually have more hospitals, universities, public transport and employment options, while rural areas may have stronger community networks but longer travel distances to services.

Developed and developing countries may differ in average income, infrastructure, healthcare and education, although there is enormous variation within both groups. Coastal and inland areas may differ because ports, tourism and major cities are often concentrated near coasts, while inland communities may face transport, climate or service-access challenges.

Disparities also exist within a single city. Some suburbs may have higher incomes, better schools, more green space and better transport than others.

When explaining a spatial disparity, avoid stereotypes. Describe the actual pattern, provide evidence, explain the causes and then link the pattern to wellbeing. A useful structure is: where is the disparity, what is different, why is it different, and what could reduce the gap?","keyTerms":[{"term":"urban","meaning":"relating to cities and densely populated areas"},{"term":"rural","meaning":"relating to countryside and lower-density settlements"},{"term":"coastal","meaning":"located near the coast"},{"term":"inland","meaning":"located away from the coast"}],"task":{"type":"group","title":"Disparity solutions lab","prompt":"Choose one pattern: urban–rural, developed–developing, coastal–inland or within one city. Identify two causes, two wellbeing impacts and two realistic responses."}}
]);