window.HW_DATA.slides.push(...[
{"number":13,"module":"measurement","title":"Why We Measure Human Wellbeing","explanation":"Geographers measure human wellbeing so they can compare places, identify patterns, monitor change and decide where support or investment may be needed. A single story can tell us a great deal about one person, but it cannot describe an entire country. Indicators help us look at larger patterns.

An indicator is a measurable piece of information, such as life expectancy, years of schooling, income or access to clean water. An index combines several indicators into one overall measure. Indexes are useful because they simplify complex information, but this simplification also creates limitations.

No measure can capture every part of wellbeing. A country may perform strongly in health and education but have serious inequality, discrimination or environmental problems. For this reason, geographers compare several indicators and ask what the data includes and what it leaves out.

Measurement is therefore not just about ranking countries. It is about using evidence carefully to understand people’s lives.","keyTerms":[{"term":"indicator","meaning":"a measurable piece of data used to show a condition"},{"term":"index","meaning":"a combined measure made from several indicators"},{"term":"data","meaning":"information collected for analysis"}],"task":{"type":"think","title":"Design a wellbeing index","prompt":"Choose five indicators you would use to compare countries. Explain why each one matters."}},
{"number":14,"module":"measurement","title":"The Human Development Index Explained","explanation":"The Human Development Index, or HDI, was created to shift attention away from economic growth alone and toward people’s capabilities and opportunities. It combines three dimensions: health, education and standard of living.

Health is measured using life expectancy at birth. Education is measured using two indicators: mean years of schooling for adults and expected years of schooling for children entering school. Standard of living is measured using Gross National Income, or GNI, per person.

The indicators are combined into a score between 0 and 1. A score closer to 1 represents higher average human development. The HDI is useful because it allows broad comparison between countries, but it is still an average. It does not directly show inequality, poverty, human security, environmental quality or political freedom.

A strong explanation of HDI should therefore do two things: explain what it measures and recognise what it cannot measure.","keyTerms":[{"term":"HDI","meaning":"Human Development Index"},{"term":"life expectancy at birth","meaning":"the average number of years a newborn is expected to live"},{"term":"mean years of schooling","meaning":"average years of education completed by adults aged 25 and over"},{"term":"expected years of schooling","meaning":"years of education a child entering school can expect to receive"},{"term":"GNI per capita","meaning":"Gross National Income divided by the population"}],"task":{"type":"match","title":"Build the HDI","prompt":"Match each dimension with its indicator, then explain why income alone would give an incomplete picture."},"external":{"label":"UNDP: Human Development Index","url":"https://hdr.undp.org/data-center/human-development-index","note":"UNDP confirms that HDI combines life expectancy, mean and expected years of schooling, and GNI per capita, while also warning that HDI captures only part of human development."}},
{"number":15,"module":"measurement","title":"Low Human Development: A Connected-Disadvantage Case","explanation":"Low human development usually results from several disadvantages occurring at the same time. Consider a country affected by prolonged conflict. Conflict can damage hospitals, schools, roads and water systems. Health services become harder to access, teachers and health workers may leave, and families may be displaced.

These conditions affect the HDI dimensions directly. Poor healthcare can reduce life expectancy. School closures and displacement can reduce years of education. Economic disruption can reduce income and employment. Food insecurity and poverty can make each of these problems worse.

The important idea is that low HDI is rarely caused by one factor. It is usually the result of connected systems. Conflict can reduce education, which can reduce future employment, which can lower income, which can reduce access to healthcare.

When analysing a low-HDI case, build a cause-and-effect chain rather than listing disconnected facts.","keyTerms":[{"term":"conflict","meaning":"violent disagreement or war that disrupts normal life"},{"term":"food insecurity","meaning":"unreliable access to enough safe and nutritious food"},{"term":"displacement","meaning":"being forced to leave one’s home"},{"term":"development outcome","meaning":"a result that affects health, education, income or living conditions"}],"task":{"type":"chain","title":"Connected disadvantage","prompt":"Build a chain starting with conflict and ending with an HDI outcome. Include at least four steps."}},
{"number":16,"module":"measurement","title":"Comparing Countries with Wellbeing Data","explanation":"Country comparisons are useful when they use the same indicators and the same year of data. A good comparison does not simply list numbers. It explains what the numbers mean for people’s lives.

For example, if one country has a much higher life expectancy than another, possible reasons might include stronger healthcare, safer water, better nutrition or lower conflict. If years of schooling differ, this may affect skills, employment and future income. If income differs greatly, access to housing, healthcare and transport may also differ.

However, comparisons must be careful. A national average can hide regional differences. Current events such as war, economic crisis or migration can change conditions quickly. Data from different years can also create misleading comparisons.

Use this structure: state the difference, support it with data, explain the likely wellbeing effect, and identify one limitation of the comparison.","keyTerms":[{"term":"comparison","meaning":"examining similarities and differences using evidence"},{"term":"national average","meaning":"a single average value for a whole country"},{"term":"reliability","meaning":"how dependable and consistent information is"}],"task":{"type":"research","title":"Country comparison","prompt":"Compare two countries using life expectancy, schooling and income. For each indicator, explain one likely wellbeing effect."}},
{"number":17,"module":"measurement","title":"Wealth Distribution and Inequality","explanation":"A country can be wealthy overall while many people still experience low wellbeing. This happens when income and wealth are distributed unevenly. If a small group controls a large share of resources, national averages may look strong even though many households have limited access to housing, healthcare or education.

This is why distribution matters as well as totals. Imagine two countries with the same average income. In one country, most people earn close to the average. In the other, a small wealthy group earns extremely high incomes while many people earn very little. The average may be similar, but everyday wellbeing is very different.

Inequality can also occur between regions, genders, age groups or cultural groups. Measuring wellbeing therefore requires looking beneath national averages.

The key question is not simply ‘How much wealth does a country have?’ but ‘Who has access to that wealth and the opportunities it creates?’","keyTerms":[{"term":"wealth distribution","meaning":"how money and assets are shared across a population"},{"term":"income inequality","meaning":"unequal distribution of income"},{"term":"average","meaning":"a central value that may hide variation within a population"}],"task":{"type":"model","title":"Same average, different reality","prompt":"Create two imaginary countries with the same average income but different distributions. Explain why their wellbeing could differ."}},
{"number":18,"module":"measurement","title":"Strengths and Limitations of HDI","explanation":"HDI is useful because it is simple, widely recognised and broader than income alone. By combining health, education and standard of living, it gives a quick overview of average human development and allows countries to be compared over time.

However, HDI has important limitations. It is a national average, so it can hide inequality between regions or groups. It does not directly measure political freedom, environmental quality, cultural wellbeing, happiness, safety or gender equality. Two countries can have similar HDI scores but very different social conditions.

This does not make HDI useless. It means it should be treated as one tool among many. A careful geographer uses HDI as a starting point and then looks at other evidence.

A strong evaluation therefore includes a judgement: HDI is useful for broad comparison, but it should not be treated as a complete picture of wellbeing.","keyTerms":[{"term":"strength","meaning":"a feature that makes a measure useful"},{"term":"limitation","meaning":"a weakness or feature that reduces usefulness"},{"term":"evaluation","meaning":"a judgement based on evidence"}],"task":{"type":"evaluate","title":"HDI judgement","prompt":"Write one strength, two limitations and a final judgement beginning: ‘Overall, HDI is useful because…, but…’"},"external":{"label":"UNDP: limits of HDI","url":"https://hdr.undp.org/data-center/human-development-index","note":"UNDP states that HDI captures only part of human development and does not directly reflect inequality, poverty, human security or empowerment."}},
{"number":19,"module":"measurement","title":"Broader Wellbeing Measures and Country Profiles","explanation":"Because wellbeing is multidimensional, broader frameworks can add information that HDI leaves out. The OECD’s wellbeing work includes areas such as housing, jobs, health, education, environment, safety, community and life satisfaction. These measures help us understand how people experience life beyond income and formal education.

A country profile combines several types of evidence. Useful information can include population, languages, religions, industries, education, major geographical features, current issues and recent news. The purpose is not to collect random facts. Each fact should help explain the country’s opportunities, challenges or wellbeing patterns.

Current news is particularly useful because statistics can change slowly while major events can affect wellbeing quickly. Conflict, natural disasters, elections, economic changes and health crises can all alter conditions.

The best country profile combines statistics, geographical context and current evidence, then explains how these shape human wellbeing.","keyTerms":[{"term":"wellbeing framework","meaning":"a set of dimensions used to organise and compare wellbeing"},{"term":"country profile","meaning":"a structured summary of key geographical, social and economic information"},{"term":"current issue","meaning":"a recent event or ongoing problem affecting a place"}],"task":{"type":"profile","title":"Build a country wellbeing profile","prompt":"Choose one country and collect one piece of evidence for health, education, income, environment, culture and a current issue."},"external":{"label":"OECD Well-being Data Monitor","url":"https://www.oecd.org/en/data/tools/well-being-data-monitor.html","note":"Use the OECD resource to extend discussion beyond HDI and compare multiple dimensions of wellbeing."}}
]);