window.HW_DATA.slides.push(...[
{"number":25,"module":"poverty","title":"What Poverty Means","explanation":"Poverty is a condition in which people do not have enough resources to achieve an acceptable standard of living. Poverty can affect food, housing, healthcare, education, transport, safety and participation in society.

Poverty is closely connected to human wellbeing because lacking resources can create problems across several dimensions at once. Low income may reduce access to healthy food and medical care. Poor housing can affect physical health. Financial stress can affect mental wellbeing. Limited education can reduce future employment opportunities.

Poverty is not only about income. It can also involve deprivation, which means lacking important goods, services or opportunities.

When studying poverty, we need to ask what people can actually access and whether they are able to meet basic needs and participate in the society around them.","keyTerms":[{"term":"poverty","meaning":"insufficient resources for an acceptable standard of living"},{"term":"deprivation","meaning":"lack of important resources, services or living conditions"},{"term":"standard of living","meaning":"the material conditions in which people live"}],"task":{"type":"brainstorm","title":"How poverty affects wellbeing","prompt":"Choose one missing resource, such as housing or food, and explain how it could affect three wellbeing factors."}},
{"number":26,"module":"poverty","title":"Absolute and Relative Poverty","explanation":"Absolute poverty refers to severe deprivation where people cannot consistently meet basic necessities such as food, clean water, shelter, clothing and essential healthcare. The focus is on whether people can meet minimum needs for survival and health.

Relative poverty is different. It compares a person’s living standard with the normal standard in the society around them. Someone may have food and shelter but still have far fewer resources than most people in their country. This can make it difficult to participate in normal social activities, access transport, use technology or provide children with the same opportunities as others.

Relative poverty is especially important in developed countries because people can experience serious disadvantage even when they are not in extreme poverty.

For global comparison, the World Bank uses an international extreme-poverty line. In June 2025, this was updated to US$3.00 per person per day using 2021 purchasing-power-parity dollars. National poverty lines are often more useful for understanding poverty within a particular country.","keyTerms":[{"term":"absolute poverty","meaning":"poverty where basic necessities cannot be consistently met"},{"term":"relative poverty","meaning":"poverty measured against the normal living standard of a society"},{"term":"poverty line","meaning":"an income threshold used to measure poverty"},{"term":"PPP","meaning":"purchasing power parity, a method for comparing what money can buy in different countries"}],"task":{"type":"classify","title":"Absolute or relative?","prompt":"Create one scenario of absolute poverty and one scenario of relative poverty. Underline the evidence that proves your classification."},"external":{"label":"World Bank: global poverty lines","url":"https://www.worldbank.org/en/news/factsheet/2025/06/05/june-2025-update-to-global-poverty-lines","note":"The World Bank updated the international extreme-poverty line to US$3.00 per person per day in June 2025."}},
{"number":27,"module":"poverty","title":"Causes of Poverty and the Poverty Trap","explanation":"Poverty can be caused by unemployment, low wages, limited education, poor health, conflict, discrimination, disasters, weak infrastructure or unequal access to land and services. Often these causes interact.

A poverty trap is a cycle that makes poverty difficult to escape. Imagine a family with very low income. They may be unable to afford transport or education. Limited education can reduce access to better-paid work. Low income then continues into the next stage of life.

Health can create a similar cycle. Poor nutrition and weak healthcare can reduce a person’s ability to work or study. Lower productivity reduces income, which makes healthcare and healthy food even harder to afford.

Breaking a poverty trap often requires more than one solution. Income support, education, healthcare, infrastructure and employment opportunities may need to work together.","keyTerms":[{"term":"poverty trap","meaning":"a self-reinforcing cycle that makes poverty difficult to escape"},{"term":"low wage","meaning":"pay that provides limited income for living costs"},{"term":"structural cause","meaning":"a broader social or economic condition that creates disadvantage"}],"task":{"type":"chain","title":"Build a poverty trap","prompt":"Create a four-step cycle using low income, education, health or employment. Then identify one intervention that could break the cycle."}},
{"number":28,"module":"poverty","title":"Disadvantage in Australia","explanation":"Disadvantage in Australia can be financial, social, geographical, educational or health-related. Financial disadvantage limits the ability to afford housing, food, transport and services. Social disadvantage can involve isolation, discrimination or weak support networks.

People in rural and remote communities may face longer distances to healthcare, education and employment. People living with disability or mental illness may face barriers to participation. Newly arrived migrants may face language or employment barriers. Aboriginal and Torres Strait Islander peoples can experience disadvantage linked to the ongoing effects of colonisation, discrimination and unequal access to services.

It is important to describe these as patterns of risk, not assumptions about individuals. Membership of a group does not automatically mean a person has low wellbeing.

The geographical question is: which barriers exist, where are they located, who is most affected, and what policies could improve access and inclusion?","keyTerms":[{"term":"financial disadvantage","meaning":"limited economic resources"},{"term":"social disadvantage","meaning":"barriers to participation, support or inclusion"},{"term":"social inclusion","meaning":"being able to participate fully in community life"},{"term":"barrier","meaning":"something that makes access or participation harder"}],"task":{"type":"discuss","title":"Risk is not destiny","prompt":"Explain why it is better to say ‘a group may face a higher risk of disadvantage’ than to assume every person in that group is disadvantaged."}},
{"number":29,"module":"poverty","title":"NGOs and Improving Human Wellbeing","explanation":"A non-governmental organisation, or NGO, is an organisation that operates independently from direct government control and works on issues such as health, humanitarian aid, education, poverty, environment or human rights.

NGOs can improve wellbeing in many ways. They may provide emergency food and shelter, build water systems, support schools, deliver healthcare, protect rights or provide training and employment support. The most important step is connecting the action to the wellbeing outcome.

For example, a clean-water project does more than provide water. It can reduce disease, save time spent collecting water, improve school attendance and reduce medical costs. One action can therefore influence physical, economic, social and educational wellbeing.

When evaluating an NGO, ask what problem it addresses, who it supports, what action it takes and what evidence shows that the action improves wellbeing.","keyTerms":[{"term":"NGO","meaning":"non-governmental organisation"},{"term":"humanitarian","meaning":"focused on reducing suffering and protecting human welfare"},{"term":"intervention","meaning":"an action taken to improve a problem or condition"}],"task":{"type":"research","title":"NGO impact chain","prompt":"Choose one Australian or international NGO. Write: problem → NGO action → immediate result → wellbeing outcome."}},
{"number":30,"module":"poverty","title":"Complex Wellbeing Challenges: The Democratic Republic of the Congo","explanation":"The Democratic Republic of the Congo is a useful case because several wellbeing challenges can occur at the same time. Conflict can displace communities, damage schools and hospitals, disrupt farming and make transport dangerous. Poverty can limit access to food, healthcare and education. Disease and poor sanitation can further reduce physical wellbeing.

These issues are interconnected. Conflict can reduce food production, which increases food insecurity. Food insecurity can weaken health. Poor health can reduce school attendance and work. Low education and employment can then make poverty harder to escape.

A strong geographical case study uses several types of evidence: HDI, life expectancy, education, child mortality, income, maps, graphs and recent news. It also considers solutions rather than only describing problems.

When proposing a solution, connect it directly to the cause. For example, if unsafe water is the problem, a relevant response might involve water infrastructure, sanitation and local maintenance. If conflict is disrupting schooling, education support must also consider safety and displacement.","keyTerms":[{"term":"food security","meaning":"reliable access to enough safe and nutritious food"},{"term":"child mortality","meaning":"deaths of children, often measured under age five"},{"term":"civil conflict","meaning":"armed conflict within a country"},{"term":"complex challenge","meaning":"a problem created by several interacting causes"}],"task":{"type":"case","title":"DRC cause–impact–solution","prompt":"Choose one issue: food security, sanitation, disease, conflict, child soldiers, poverty or disasters. Define it, give evidence, explain the wellbeing impact and recommend one realistic response."}}
]);