window.HW_DATA.slides.push(...[
{"number":20,"module":"sustainable","title":"What Sustainable Development Means","explanation":"Sustainable development means improving people’s lives today without reducing the ability of future generations to meet their own needs. The idea is based on balance. Development can create jobs, housing, roads, energy and services, but it can also damage ecosystems or use resources faster than they can recover.

A sustainable decision considers economic, social and environmental outcomes together. For example, a new industry may create employment and income, which improves economic wellbeing. But if it pollutes a river, it may reduce physical and environmental wellbeing. A more sustainable approach would create jobs while also protecting water quality.

Sustainability is therefore not about stopping development. It is about asking whether development can continue over time without causing unacceptable harm.

The central question is: can this decision improve wellbeing now and still leave future generations with healthy environments, resources and opportunities?","keyTerms":[{"term":"sustainable development","meaning":"development that meets present needs without reducing future generations’ ability to meet theirs"},{"term":"future generations","meaning":"people who will live in the future"},{"term":"trade-off","meaning":"a situation where gaining one benefit may involve a cost elsewhere"}],"task":{"type":"redesign","title":"Make it sustainable","prompt":"Choose a development project such as a road, mine, housing estate or farm. Identify one benefit, one risk and one change that would make it more sustainable."}},
{"number":21,"module":"sustainable","title":"From the Millennium Development Goals to the SDGs","explanation":"The Millennium Development Goals, or MDGs, were a global development framework used from 2000 to 2015. They focused strongly on extreme poverty and basic human needs such as health and education.

In 2015, the United Nations adopted the Sustainable Development Goals, or SDGs, as part of the 2030 Agenda. The SDGs expanded the focus. They still address poverty, hunger, health and education, but they also include inequality, climate change, sustainable cities, clean energy, peace, responsible consumption and ecosystem protection.

The shift from MDGs to SDGs shows that development is now understood more broadly. Human wellbeing depends on social, economic and environmental systems working together.

The SDGs also apply to all countries, not only lower-income countries. Australia, for example, still faces challenges involving inequality, housing, climate, sustainable cities and environmental protection.","keyTerms":[{"term":"MDGs","meaning":"Millennium Development Goals, used from 2000 to 2015"},{"term":"SDGs","meaning":"17 Sustainable Development Goals adopted in 2015"},{"term":"2030 Agenda","meaning":"the United Nations framework for achieving the SDGs by 2030"}],"task":{"type":"compare","title":"MDGs vs SDGs","prompt":"Write two ways the SDGs are broader than the MDGs."},"external":{"label":"United Nations Sustainable Development Goals","url":"https://sdgs.un.org/goals","note":"The United Nations lists the 17 SDGs and explains their role within the 2030 Agenda."}},
{"number":22,"module":"sustainable","title":"The 17 Sustainable Development Goals as a Connected System","explanation":"The 17 SDGs are designed to address different parts of human wellbeing and environmental sustainability. Goals include ending poverty and hunger, improving health and education, achieving gender equality, providing clean water and energy, supporting decent work, reducing inequality, building sustainable cities, taking climate action and protecting ecosystems.

The goals are interconnected. Improving clean water can improve health and school attendance. Better education can improve employment and income. Sustainable cities can improve transport, air quality and safety. Climate action can protect food security, housing and health.

This means progress in one goal can support progress in others. The reverse is also true. Failure in one area can create problems elsewhere.

When analysing an SDG, do not treat it as an isolated target. Ask which wellbeing factors it affects and which other goals it connects to.","keyTerms":[{"term":"interconnected","meaning":"linked so that changes in one area affect another"},{"term":"target","meaning":"a specific result that a goal aims to achieve"},{"term":"global goal","meaning":"an internationally agreed objective"}],"task":{"type":"web","title":"SDG connection web","prompt":"Choose one SDG and draw arrows to at least three other SDGs that it could influence. Explain each connection."},"external":{"label":"United Nations Sustainable Development Goals","url":"https://sdgs.un.org/goals","note":"Use the official list to explore the 17 goals and their targets."}},
{"number":23,"module":"sustainable","title":"Evaluating Progress Toward an SDG","explanation":"To evaluate progress toward a Sustainable Development Goal, we need more than a description of the goal. We need evidence of action and evidence of change.

For example, if a government says it is working toward clean water and sanitation, we can ask what policies or projects have been introduced, how many people gained access to safe water, and whether water quality improved. We should also ask whether benefits reached rural and disadvantaged communities.

Comparison can strengthen evaluation. Two countries may pursue the same goal using different strategies. One may focus on infrastructure, while another focuses on regulation or community programs.

A strong evaluation follows this pattern: identify the goal, describe the action, provide evidence of progress, explain the wellbeing effect, and make a judgement about how effective the action appears to be.","keyTerms":[{"term":"policy","meaning":"a planned course of action adopted by a government or organisation"},{"term":"progress","meaning":"movement toward achieving a goal"},{"term":"effectiveness","meaning":"how well an action achieves its intended result"}],"task":{"type":"research","title":"Compare two countries","prompt":"Choose one SDG. Find one action from Australia and one action from another country. Decide which action appears more effective and justify your judgement."}},
{"number":24,"module":"sustainable","title":"Using Human Development Data to Explain Differences","explanation":"Human development data becomes most useful when it is used to explain differences between places. Imagine two countries with very different HDI scores. A strong comparison uses evidence from health, education and income, then explains how the differences affect people’s lives.

Higher life expectancy may reflect stronger healthcare, nutrition or sanitation. More years of schooling may create greater employment opportunities. Higher income may improve access to housing and services. The goal is not to label one country as simply ‘good’ and another as ‘bad’. The goal is to explain the conditions that produce different outcomes.

Data should also be treated as evidence from a particular time. Development indicators change, and countries can improve or decline.

A useful comparison therefore includes numbers, explanation and caution. It shows what the data suggests without pretending that one score can describe every person.","keyTerms":[{"term":"human development data","meaning":"evidence about health, education and living standards"},{"term":"evidence-based comparison","meaning":"comparison supported by relevant data"},{"term":"context","meaning":"the surrounding conditions that help explain data"}],"task":{"type":"exam","title":"Four-mark comparison","prompt":"Use three indicators from two countries. For each difference, explain how it could affect human wellbeing."}}
]);