window.HW_DATA.slides.push(...[
{"number":1,"module":"wellbeing","title":"What Human Wellbeing Means","explanation":"Human wellbeing means the overall quality of a person’s life. It is not just about being happy, and it is not just about having money. A person can have a high income but still experience poor health, loneliness, stress or a lack of freedom. In the same way, a person with a modest income may still have strong relationships, a sense of purpose, cultural connection and a safe community.

When geographers study human wellbeing, they look at the conditions that help people live healthy, secure, meaningful and fulfilling lives. These conditions include access to food, clean water, healthcare, housing, education, employment, supportive relationships, a safe environment, cultural identity and political rights. Wellbeing is therefore multidimensional. This means that it has many connected parts.

It is also important to remember that wellbeing can be understood differently by different people and communities. Culture, values, age, location and life experiences can influence what a ‘good life’ means. The key idea is that human wellbeing is about how well people are able to live, meet their needs, participate in society and pursue opportunities that matter to them.","keyTerms":[{"term":"human wellbeing","meaning":"the overall quality of life of a person or community"},{"term":"quality of life","meaning":"how healthy, safe, secure, connected and satisfied a person is in life"},{"term":"multidimensional","meaning":"made up of several different but connected parts"}],"task":{"type":"think","title":"What makes a good life?","prompt":"Write five things that you think people need for a good quality of life. Then label each as physical, economic, social, environmental, cultural, emotional or political."}},
{"number":2,"module":"wellbeing","title":"Needs, Wants, Happiness and Place","explanation":"A useful way to begin thinking about wellbeing is to separate needs from wants. A need is something that is necessary for a safe, healthy or dignified life, such as food, clean water, shelter, healthcare and personal safety. A want is something a person would like to have, but can live without. The difference is not always simple, because some things may be essential in one society and less important in another. For example, reliable internet access may not be a basic survival need, but it can be extremely important for education, employment and social connection.

Happiness is also connected to wellbeing, but the two ideas are not identical. Happiness is mainly about how people feel, while wellbeing includes both feelings and measurable living conditions. Someone may feel happy for a short time even while facing serious financial or health problems. Another person may have safe housing, education and healthcare but still feel isolated or stressed.

Place matters too. Where people live can influence access to jobs, schools, hospitals, transport, green space, clean air and community support. This is why geography is important when we study wellbeing. Wellbeing is shaped by both personal experiences and the opportunities available in particular places.","keyTerms":[{"term":"need","meaning":"something necessary for basic living, health or dignity"},{"term":"want","meaning":"something desirable but not essential"},{"term":"place","meaning":"the location and environment where people live"},{"term":"happiness","meaning":"a person’s feeling of satisfaction, pleasure or positive emotion"}],"task":{"type":"discuss","title":"Need or want?","prompt":"Classify: clean water, a smartphone, safe housing, a car, healthcare, streaming subscriptions, friendship, reliable internet. Explain any examples that could fit more than one category."}},
{"number":3,"module":"wellbeing","title":"Material and Non-Material Wellbeing","explanation":"Human wellbeing includes both material and non-material dimensions. Material wellbeing refers to physical resources and living conditions that people can access. Examples include income, food, housing, transport, electricity, healthcare, clothing and technology. These resources matter because they help people meet their needs and participate in everyday life.

Non-material wellbeing refers to important parts of life that are not mainly about possessions or money. These include relationships, safety, identity, freedom, respect, belonging, purpose, cultural connection and the ability to practise beliefs. These things can have a powerful effect on quality of life even though they are difficult to measure in dollars.

The two dimensions are connected. For example, a stable income may help a family access safe housing, but housing alone does not guarantee that people feel secure or connected. A strong community can provide emotional support even when income is limited. A government may improve material living conditions through infrastructure, while people may still experience discrimination or political exclusion.

A strong understanding of wellbeing therefore looks beyond wealth. Money and services matter, but so do dignity, identity, connection and freedom.","keyTerms":[{"term":"material wellbeing","meaning":"wellbeing linked to resources, possessions and living conditions"},{"term":"non-material wellbeing","meaning":"wellbeing linked to relationships, identity, freedom, purpose and belonging"},{"term":"dignity","meaning":"the right to be treated with respect and worth"}],"task":{"type":"sort","title":"Material or non-material?","prompt":"Sort six examples into material and non-material wellbeing. Then identify two examples that are connected to both."}},
{"number":4,"module":"wellbeing","title":"The Seven Factors of Human Wellbeing","explanation":"Human wellbeing can be organised into seven major factors. Physical wellbeing is about health and the basic conditions needed to stay healthy, including clean water, nutritious food, healthcare, safe housing and sanitation. Economic wellbeing is about income, employment and financial security. Social wellbeing focuses on relationships, support networks, community participation and connection with others.

Environmental wellbeing is shaped by the quality and safety of the natural and built environment. Clean air, safe water, green space and protection from hazards can improve wellbeing, while pollution, disasters and unsafe surroundings can reduce it. Mental and emotional wellbeing includes the ability to cope with stress, maintain a positive sense of self and experience purpose and emotional stability.

Cultural and spiritual wellbeing is linked to identity, traditions, language, beliefs and connection to culture or faith. Political wellbeing relates to rights, freedom, representation and the ability to participate in decisions that affect people’s lives.

These factors are not separate boxes. They overlap. A person who loses a job may experience economic stress, which can affect housing, physical health, mental health and family relationships. This is why wellbeing should be understood as a connected system rather than a checklist.","keyTerms":[{"term":"physical wellbeing","meaning":"health and access to conditions needed to stay healthy"},{"term":"economic wellbeing","meaning":"income, employment and financial security"},{"term":"social wellbeing","meaning":"relationships, support and participation in community"},{"term":"environmental wellbeing","meaning":"the quality and safety of the environment"},{"term":"mental and emotional wellbeing","meaning":"coping, self-image, emotional health and purpose"},{"term":"cultural and spiritual wellbeing","meaning":"identity, traditions, beliefs and cultural connection"},{"term":"political wellbeing","meaning":"rights, freedom and participation in decision-making"}],"task":{"type":"apply","title":"Factor match","prompt":"Create one real-life example for each of the seven factors. Then identify one example that could affect at least three factors at the same time."},"external":{"label":"Beyond Blue: whole-person mental wellbeing","url":"https://www.beyondblue.org.au/mental-health/wellbeing","note":"Beyond Blue describes mental wellbeing as involving the whole person and balancing physical, mental, social and emotional aspects. This is a useful real-life example of how different wellbeing dimensions interact."}},
{"number":5,"module":"wellbeing","title":"How Wellbeing Factors Interact","explanation":"One of the most important ideas in this topic is that wellbeing factors influence each other. Imagine a person who develops a serious illness. Their physical wellbeing is affected first, but the impact may spread further. They may be unable to work, which reduces income and affects economic wellbeing. Financial pressure may increase stress and reduce mental wellbeing. They may spend less time with friends and community, affecting social wellbeing.

The same connection can work positively. Good education can improve employment opportunities. Stable employment can increase income. Higher income can improve access to housing, healthy food and healthcare. Feeling secure can reduce stress and make it easier to participate in social and cultural activities.

This is why explanations in Geography should show cause and effect. It is not enough to say that income affects wellbeing. A stronger explanation shows how: stable income can help people afford basic needs and services, which can improve physical security, reduce stress and increase opportunities.

When you analyse wellbeing, always ask two questions: What factor is directly affected? What other factors could be affected next?","keyTerms":[{"term":"enhance","meaning":"to improve or strengthen"},{"term":"hinder","meaning":"to reduce or make more difficult"},{"term":"cause and effect","meaning":"showing how one condition leads to another outcome"}],"task":{"type":"chain","title":"Wellbeing dominoes","prompt":"Choose one event such as job loss, good education, pollution or supportive friendships. Build a four-step chain showing how it affects several wellbeing factors."}},
{"number":6,"module":"wellbeing","title":"Opportunity, Advantage and Unequal Starting Points","explanation":"People do not all begin life with the same opportunities or barriers. Some people grow up with stable housing, strong schools, healthcare, financial security and supportive networks. Others may experience poverty, discrimination, conflict, disability, poor infrastructure or limited access to services. These differences can shape wellbeing even when people work equally hard.

An advantage is a condition that makes access or success easier. A disadvantage is a condition that creates barriers. Privilege refers to advantages that a person may have because of social, economic or political circumstances. These ideas do not mean that individual effort is unimportant. They mean that effort takes place within different conditions.

For example, two students may be equally motivated, but one has reliable internet, a quiet study space and family support, while the other works after school and shares a crowded home. Their effort may be similar, but their opportunities are not identical.

Understanding unequal starting points helps explain why wellbeing outcomes differ between people and places. It also introduces the idea of regional disparities, where access to resources and opportunities varies geographically.","keyTerms":[{"term":"opportunity","meaning":"a chance to access something or achieve an outcome"},{"term":"advantage","meaning":"a condition that makes access or success easier"},{"term":"disadvantage","meaning":"a condition that creates barriers"},{"term":"privilege","meaning":"an advantage available to some people because of their circumstances"}],"task":{"type":"reflect","title":"Equal effort, unequal conditions","prompt":"Explain why equal effort does not always produce equal outcomes. Use one school-based or community-based example."}}
]);